### PR TITLE
add an example of using static resources

### PR DESCRIPTION
**Pull request by sbondaryev**
Issue #82:  Ring server fails to start when img folder does not exists

### CODE REVIEW

**Comment by lacarmen** [comment]
This doesn't actually render the image properly. When creating a new cryogen project this creates cryogen.png but it's "corrupted".

**Comment by sbondaryev** [comment]
fixed, maybe should ask to add  binary-renderer function to leiningen/new/templates.clj
as i didn't found a facility to generate binary files out-of-the-box?

**Comment by yogthos** [comment]
That's actually fairly easy to do, e.g:

```clojure
(defn resource [resource]
  (-> (Thread/currentThread)
      (.getContextClassLoader)
      (.getResource (str "leiningen/new/luminus/core/resources/" resource)))

["resources/public/favicon.ico"  (resource "site/favicon.ico")]
```

**Comment by sbondaryev** [comment]
Yes, but I bother about the leiningen directory path hardcoded

**Comment by yogthos** [comment]
That shouldn't be an issue as that's what's going to be packaged in the jar when the template is deployed.

**Comment by sbondaryev** [comment]
it uses your resource function now, thanks

**Comment by lacarmen** [comment]
Looks good

**Pull request merged**
