### PR TITLE
Add author.html to template

### PR DESCRIPTION
**Pull request by tomasz-biernacki**
Related to https://github.com/cryogen-project/cryogen-core/pull/63 and https://github.com/cryogen-project/cryogen-docs/pull/6

### CODE REVIEW

**Comment by tomasz-biernacki** [comment]
screen shot 2016-02-10 at 22 51 25

**Comment by tomasz-biernacki** [comment]
Then it's up to the user to provide correct link in the views.

**Comment by lacarmen** [comment]
Clojars build will be up later

**Comment by tomasz-biernacki** [comment]
No problem, just check if everything is OK for you ;)

**Comment by lacarmen** [comment]
Just did the push to Clojars; the template is on 0.2.37 now.

**Comment by lacarmen** [comment]
Scratch that, it's version 0.2.38 :) I added the new `:author-root-uri ` key to the default config.

**Comment by tomasz-biernacki** [comment]
@lacarmen ok :)
If so, if you want, you can also update the README (https://github.com/cryogen-project/cryogen#site-configuration)

**Comment by lacarmen** [comment]
@tomasz-biernacki It's okay, I got it :)

**Comment by tomasz-biernacki** [comment]
:+1:

**Pull request merged**
