### PR TITLE
Clean URLs with and without trailing slash

### PR DESCRIPTION
**Pull request by niamu**
This pull request is the other half of the work related to https://github.com/cryogen-project/cryogen-core/pull/119.

### CODE REVIEW

**Comment by lacarmen** [comment]
I had to update the `server.clj` code so that navigating to `/blog` would work with `:no-trailing-slash` and `:dirty`

```
(defn update-path 
  [config req-uri]
  (if (or (= req-uri "") (= req-uri "/") (= req-uri (.substring (:blog-prefix config) 1)))
    (path req-uri "index.html")
    (path (str req-uri ".html"))))

(defn wrap-subdirectories
  [handler]
  (fn [request]
    (let [{:keys [clean-urls] :as config} (read-config)
          req-uri (.substring (url-decode (:uri request)) 1)
          res-path (condp = clean-urls
                     :trailing-slash (path req-uri "index.html")
                     :no-trailing-slash (update-path config req-uri) 
                     :dirty (update-path config req-uri))]
      (or (resource-response res-path {:root "public"})
          (handler request)))))
```

**Comment by lacarmen** [comment]
@niamu Could you double check that we have all the cases covered? I tested everything myself but a 2nd pair of eyes is always better :)

**Comment by niamu** [comment]
Yup, you're right. I must have not had a `:blog-prefix` set when testing that case. I've resolved it now and confirmed the other cases are still working.

**Comment by lacarmen** [comment]
Thanks @niamu, looks like everything is working! 

I'm going to merge this + the cryogen-core change but I will hold off on the docs one until I release everything together with cryogen-project/cryogen-core#117

**Comment by lacarmen** [comment]
Actually, I changed my mind. I'm going to do two releases for the two changes since the project structure one will introduce breaking changes and users might want to get the clean-urls change but not the project structure change.

**Pull request merged**
