### PR TITLE
auto-refresh

### PR DESCRIPTION
**Pull request by matsu911**
auto refresh browser when any file under public directory

### CODE REVIEW

**Comment by lacarmen** [comment]
This doesn't seem to be working for me. Can you provide an example of the workflow that you used in order to see the auto-refreshing?

**Comment by matsu911** [comment]
autho-refresh providers browser live reload feature.
This is very useful when you check outputs with browser without manual browser reload.

**Comment by lacarmen** [comment]
I understand, but I tried out your changes and I'm still having to manually refresh the browser. Is there something I'm missing?

**Comment by matsu911** [comment]
Can you make sure that matsu911/ring-server 0.4.1 is used?
I guess ring-server 0.4.0 was used on your pc.

**Comment by lacarmen** [comment]
Okay, looks like my .m2 folder got in a weird state. However, I'm getting an exception upon starting the server.

```
carmen@lalabook [~/s/t/tmp] ⋊> lein ring server                                                                                                                                                                                                                  [2/2373]
2016-10-22 13:29:58.598:INFO::main: Logging initialized @881ms
Exception in thread "main" java.lang.Exception: Directory does not exist: , compiling:(server.clj:29:18)
        at clojure.lang.Compiler$InvokeExpr.eval(Compiler.java:3657)
        at clojure.lang.Compiler$InvokeExpr.eval(Compiler.java:3651)
        at clojure.lang.Compiler$InvokeExpr.eval(Compiler.java:3651)
        at clojure.lang.Compiler$DefExpr.eval(Compiler.java:451)
        at clojure.lang.Compiler.eval(Compiler.java:6932)
        at clojure.lang.Compiler.load(Compiler.java:7379)
        at clojure.lang.RT.loadResourceScript(RT.java:372)
        at clojure.lang.RT.loadResourceScript(RT.java:363)
        at clojure.lang.RT.load(RT.java:453)
        at clojure.lang.RT.load(RT.java:419)
        at clojure.core$load$fn__5677.invoke(core.clj:5893)
        at clojure.core$load.invokeStatic(core.clj:5892)
        at clojure.core$load.doInvoke(core.clj:5876)
        at clojure.lang.RestFn.invoke(RestFn.java:408)
        at clojure.core$load_one.invokeStatic(core.clj:5697)
        at clojure.core$load_one.invoke(core.clj:5692)
        at clojure.core$load_lib$fn__5626.invoke(core.clj:5737)
        at clojure.core$load_lib.invokeStatic(core.clj:5736)
        at clojure.core$load_lib.doInvoke(core.clj:5717)
        at clojure.lang.RestFn.applyTo(RestFn.java:142)
        at clojure.core$apply.invokeStatic(core.clj:648)
        at clojure.core$load_libs.invokeStatic(core.clj:5774)
        at clojure.core$load_libs.doInvoke(core.clj:5758)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.core$apply.invokeStatic(core.clj:648)
        at clojure.core$require.invokeStatic(core.clj:5796)
        at clojure.core$require.doInvoke(core.clj:5796)
        at clojure.lang.RestFn.invoke(RestFn.java:436)
        at user$eval5.invokeStatic(form-init8939294336775262323.clj:1)
        at user$eval5.invoke(form-init8939294336775262323.clj:1)
        at clojure.lang.Compiler.eval(Compiler.java:6927)
        at clojure.lang.Compiler.eval(Compiler.java:6916)
        at clojure.lang.Compiler.load(Compiler.java:7379)
        at clojure.lang.Compiler.loadFile(Compiler.java:7317)
        at clojure.main$load_script.invokeStatic(main.clj:275)
        at clojure.main$init_opt.invokeStatic(main.clj:277)
        at clojure.main$init_opt.invoke(main.clj:277)
        at clojure.main$initialize.invokeStatic(main.clj:308)
        at clojure.main$null_opt.invokeStatic(main.clj:342)
        at clojure.main$null_opt.invoke(main.clj:339)
        at clojure.main$main.invokeStatic(main.clj:421)
        at clojure.main$main.doInvoke(main.clj:384)
        at clojure.lang.RestFn.invoke(RestFn.java:421)
        at clojure.lang.Var.invoke(Var.java:383)
        at clojure.lang.AFn.applyToHelper(AFn.java:156)
        at clojure.lang.Var.applyTo(Var.java:700)
        at clojure.main.main(main.java:37)
Caused by: java.lang.Exception: Directory does not exist:
        at ring.middleware.file$ensure_dir.invokeStatic(file.clj:17)
        at ring.middleware.file$ensure_dir.invoke(file.clj:12)
        at ring.middleware.file$wrap_file.invokeStatic(file.clj:41)
        at ring.middleware.file$wrap_file.doInvoke(file.clj:30)
        at clojure.lang.RestFn.applyTo(RestFn.java:142)
        at clojure.lang.Compiler$InvokeExpr.eval(Compiler.java:3652)
        ... 46 more
Subprocess failed
```

**Comment by matsu911** [comment]
Seems like resources/public does not exist on your side.
Can you do `lein run` and try again?

**Comment by lacarmen** [comment]
Doing `lein run` before `lein ring server` seems to do the trick but ideally this shouldn't have to happen. If someone creates a new Cryogen project then they won't have a resources/public folder yet.

**Comment by matsu911** [comment]
Added prep-dirs leiningen task and set it to :prep-tasks.

**Comment by lacarmen** [comment]
Okay, the server starts up properly now. The only thing left is that `http://localhost:3000` no longer redirects to `http://localhost:3000/blog-prefix/` if the prefix is specified.

**Comment by matsu911** [comment]
Sorry, I removed the direct code carelessly.
Added redirect code again.

**Comment by lacarmen** [comment]
Sorry, one more thing! I get a 404 when the page auto-refreshes. The url remains correct and there are no errors in the console but no content can be found.

**Comment by matsu911** [comment]
Clean public folder triggers refresh, but regenerate files takes takes about 1 sec, so browser refresh may hit 404.
I have an idea to solve this issue.
I'll make another commit later.

**Comment by matsu911** [comment]
Please try with this PR.
https://github.com/cryogen-project/cryogen-core/pull/72

**Comment by lacarmen** [comment]
This solution seems a little hacky. Is there a better way to trigger the refresh?

**Pull request closed without merging**
